services:
  postgres:
    image: "postgres:15.4"
    ports:
      - "15432:5432"
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    deploy:
      resources:
        limits:
          cpus: 1
#          memory: 2G
        reservations:
          cpus: 1
#          memory: 2G
      
